export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIE = "FETCH_MOVIE";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
